### ISSUE TITLE
Error when retrieving metrics with Quality-time as source

### ISSUE THREAD

**Issue by Erik-Stel** [ICTU/quality-time#1154]
When using Quality-time as source for a "Metrics" metric, the following error is shown. It seems the api_url is not a Future object.

```
Connection error
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 86, in __safely_get_source_responses
    responses = await self._get_source_responses(api_url := await self._api_url())
  File "/home/collector/source_collectors/api_source_collectors/quality_time.py", line 24, in _get_source_responses
    responses = await super()._get_source_responses(URL(f"{urls[0]}/reports"))
  File "/home/collector/base_collectors/source_collector.py", line 105, in _get_source_responses
    return list(await asyncio.gather(*tasks))
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 996, in send
    return self._coro.send(arg)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
RuntimeError: await wasn't used with future
```

**Comment by fniessink** [comment]
The issue doesn't seem specific to the "Metrics" metric. When trying to reproduce the issue locally, I got the same error with three different metrics that have SonarQube as source, while the Metrics metric did return the proper results. Traceback is almost identical:

```
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 86, in __safely_get_source_responses
    responses = await self._get_source_responses(api_url := await self._api_url())
  File "/home/collector/source_collectors/api_source_collectors/sonarqube.py", line 173, in _get_source_responses
    return await super()._get_source_responses(*(urls + (resolved_issues_api_url, all_issues_api_url)))
  File "/home/collector/source_collectors/api_source_collectors/sonarqube.py", line 77, in _get_source_responses
    return await super()._get_source_responses(*api_urls)
  File "/home/collector/source_collectors/api_source_collectors/sonarqube.py", line 25, in _get_source_responses
    response = (await super()._get_source_responses(show_component_url))[0]
  File "/home/collector/base_collectors/source_collector.py", line 105, in _get_source_responses
    return list(await asyncio.gather(*tasks))
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 996, in send
    return self._coro.send(arg)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1006, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 920, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
RuntimeError: await wasn't used with future
```

**Comment by fniessink** [comment]
Also, the error doesn't happen every time. Maybe it's connected to the occurrence of a timeout?

**Comment by Erik-Stel** [comment]
Difficult to tell. Changing the URL will directly show 'URL connection OK'. So it seams the quality-time instance (in our case) is present and alive. Assuming the collector did itself perform this check and not my browser.

**Comment by fniessink** [comment]
> Assuming the collector did itself perform this check and not my browser.

It's the server component that does the URL check (the collector wakes up once a minute so having the collector do the URL check would be too slow).

**Comment by fniessink** [comment]
So, what I found so far:

- The traceback hides the actual error, which is an `OSError: [Errno 9] Bad file descriptor`, which becomes visible in the logging when adding `debug=True` to `asyncio.run()`.
- That error is caused by a mistake in the Quality-time URL: it should include "www". 
- However, after adding "www" to the Quality-time URL, another error surfaces:

```
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 86, in __safely_get_source_responses
    responses = await self._get_source_responses(api_url := await self._api_url())
  File "/home/collector/source_collectors/api_source_collectors/quality_time.py", line 28, in _get_source_responses
    return responses + await super()._get_source_responses(*measurement_urls)
  File "/home/collector/base_collectors/source_collector.py", line 105, in _get_source_responses
    return list(await asyncio.gather(*tasks))
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 999, in throw
    self._coro.throw(arg)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

- The timeout is a genuine bug in Quality-time: after retrieving the reports, Quality-time also retrieves all measurements for all metrics, which is quite a bit of data, and hence the timeout. This is not necessary: the recent measurements are included in the report and don't need to be retrieved separately.

Open issues:

- I'm still not sure why I saw the same traceback for SonarQube metrics.
- I still don't know how to properly prevent the RuntimeError from hiding underlying exceptions.
- I'm not entirely sure why the "www" is needed in the Quality-time URL.
