### ISSUE TITLE
Changing OWASP Dependency Check Security Warning Status to 'False positive' results in Internal Server Error

### ISSUE THREAD

**Issue by stevenwennekes** [ICTU/quality-time#1238]
Changing the OWASP Dependency Check Security Warning Status to 'False positive' results in Internal Server Error.

![image](https://user-images.githubusercontent.com/4834927/84984200-aaccf600-b13a-11ea-833f-e38f2099cd34.png)

After changing the value in the dropdown the POST to the server with status 'false_positive' responses with code 500. The UI does not give any feedback and the Security Warning status stays at 'Unconfirmed'.

**Comment by Erik-Stel** [comment]
I can confirm have the same issue. Both using Brave (a Chromium based browser) and using Firefox.

**Comment by fniessink** [comment]
```
2020-06-18T12:02:19.068Z Traceback (most recent call last):
2020-06-18T12:02:19.068Z File "/usr/local/lib/python3.8/site-packages/bottle.py", line 868, in _handle
2020-06-18T12:02:19.068Z return route.call(**args)
2020-06-18T12:02:19.068Z File "/usr/local/lib/python3.8/site-packages/bottle.py", line 1748, in wrapper
2020-06-18T12:02:19.068Z rv = callback(*a, **ka)
2020-06-18T12:02:19.069Z File "/home/server/routes/plugins/authentication_plugin.py", line 31, in wrapper
2020-06-18T12:02:19.069Z File "/home/server/routes/plugins/injection_plugin.py", line 39, in wrapper
2020-06-18T12:02:19.069Z return callback(*args, **kwargs)
2020-06-18T12:02:19.069Z File "/home/server/routes/measurement.py", line 50, in set_entity_attribute
2020-06-18T12:02:19.069Z entity_description = "/".join([entity[key] for key in entity.keys() if key not in
("key", "url")])
2020-06-18T12:02:19.069Z return callback(*args, **kwargs)
2020-06-18T12:02:19.070Z TypeError: sequence item 2: expected str instance, int found
```

**Comment by fniessink** [comment]
This is the same issue as https://github.com/ICTU/quality-time/issues/1230 which has been fixed in the master branch but hasn't been released yet.
