### ISSUE TITLE
Parse latest XSD version of OWASP Dependency-Check

### ISSUE THREAD

**Issue by bdtesty** [ICTU/quality-time#1460]
Parsing a latest dep check report gives the following error:

```
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 130, in __safely_parse_source_responses
    measurement = await self._parse_source_responses(responses)
  File "/home/collector/source_collectors/file_source_collectors/owasp_dependency_check.py", line 30, in _parse_source_responses
    tree, namespaces = await parse_source_response_xml_with_namespace(response, self.allowed_root_tags)
  File "/home/collector/collector_utilities/functions.py", line 27, in parse_source_response_xml_with_namespace
    tree = await parse_source_response_xml(response, allowed_root_tags)
  File "/home/collector/collector_utilities/functions.py", line 20, in parse_source_response_xml
    raise AssertionError(f'The XML root element should be one of "{allowed_root_tags}" but is "{tree.tag}"')
AssertionError: The XML root element should be one of "['{https://jeremylong.github.io/DependencyCheck/dependency-check.2.0.xsd}analysis', '{https://jeremylong.github.io/DependencyCheck/dependency-check.2.1.xsd}analysis', '{https://jeremylong.github.io/DependencyCheck/dependency-check.2.2.xsd}analysis', '{https://jeremylong.github.io/DependencyCheck/dependency-check.2.3.xsd}analysis']" but is "{https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd}analysis"
```

components\collector\src\source_collectors\file_source_collectors\owasp_dependency_check.py:19

```    allowed_root_tags = [f"{{https://jeremylong.github.io/DependencyCheck/dependency-check.{version}.xsd}}analysis"
                         for version in ("2.0", "2.1", "2.2", "2.3")] ```

Should allow XSD version 2.5 but is there any reason why we should not allow any XSD version ?

**Comment by fniessink** [comment]
The reason for the check is that we've been bitten in the past by changes to the OWASP Dependency Check XSD that caused Quality-time to (silently) report incorrect data.
