### ISSUE TITLE
Intermittent failures to parse Checkmarx data

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#1462]
```
Parse error
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 130, in __safely_parse_source_responses
    measurement = await self._parse_source_responses(responses)
  File "/home/collector/source_collectors/api_source_collectors/cxsast.py", line 84, in _parse_source_responses
    stats = await responses[0].json()
  File "/home/collector/source_model/responses.py", line 22, in __getitem__
    return self.__responses[key]
IndexError: list index out of range
```

**Comment by fniessink** [comment]
Can't reproduce reliably.
