### ISSUE TITLE
Error when running latest version

### ISSUE THREAD

**Issue by bdtesty** [ICTU/quality-time#1615]
Hi,

I'm receiving an error when running the latest version:

```docker-compose build```

Start the containers:

```docker-compose up```

Docker logs 

```INFO:root:172.19.0.12 - - [2020-10-27 07:45:15] "GET /api/v3/reports?report_date=3000-01-31T23:00:00.000Z HTTP/1.1" 500 925 0.118314
INFO:root:127.0.0.1 - - [2020-10-27 07:45:25] "GET /api/health HTTP/1.1" 200 109 0.000631
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/server/routes/plugins/injection_plugin.py", line 39, in wrapper
    return callback(*args, **kwargs)
  File "/home/server/routes/reports.py", line 25, in get_reports
    hide_credentials(data_model, *overview["reports"])
  File "/home/server/model/transformations.py", line 17, in hide_credentials
    if parameter_value and is_password_parameter(data_model, source["type"], parameter_key):
  File "/home/server/model/queries.py", line 10, in is_password_parameter
    parameter_type = data_model["sources"][source_type]["parameters"].get(parameter, dict(type="password"))["type"]
KeyError: 'generic'
INFO:root:172.19.0.12 - - [2020-10-27 07:45:25] "GET /api/v3/reports?report_date=3000-01-31T23:00:00.000Z HTTP/1.1" 500 925 0.007792
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/server/routes/plugins/injection_plugin.py", line 39, in wrapper
    return callback(*args, **kwargs)
  File "/home/server/routes/reports.py", line 25, in get_reports
    hide_credentials(data_model, *overview["reports"])
  File "/home/server/model/transformations.py", line 17, in hide_credentials
    if parameter_value and is_password_parameter(data_model, source["type"], parameter_key):
  File "/home/server/model/queries.py", line 10, in is_password_parameter
    parameter_type = data_model["sources"][source_type]["parameters"].get(parameter, dict(type="password"))["type"]
KeyError: 'generic'

INFO:root:172.19.0.12 - - [2020-10-27 07:45:35] "GET /api/v3/datamodel?report_date=3000-01-31T23:00:00.000Z HTTP/1.1" 304 66 0.006707
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/server/routes/plugins/injection_plugin.py", line 39, in wrapper
    return callback(*args, **kwargs)
  File "/home/server/routes/reports.py", line 25, in get_reports
    hide_credentials(data_model, *overview["reports"])
  File "/home/server/model/transformations.py", line 17, in hide_credentials
    if parameter_value and is_password_parameter(data_model, source["type"], parameter_key):
  File "/home/server/model/queries.py", line 10, in is_password_parameter
    parameter_type = data_model["sources"][source_type]["parameters"].get(parameter, dict(type="password"))["type"]
KeyError: 'generic'
INFO:root:172.19.0.12 - - [2020-10-27 07:45:35] "GET /api/v3/reports?report_date=3000-01-31T23:00:00.000Z HTTP/1.1" 500 925 0.104235
WARNING:root:LDAP error for user  <unknown email>: list index out of range```

**Comment by fniessink** [comment]
We renamed the source 'generic' to 'generic_json' while developing the generic JSON for security warnings feature. It seems you still have a report in your database that has a metric with a 'generic' (instead of 'generic_json') source. I'm assuming this is a testdatabase? You can simply use Mongo Express to rename it by hand.

**Comment by bdtesty** [comment]
Cleared all my docker images incl. data and database volumes and now it works  again.  Thanks
