### ISSUE TITLE
Make sure the server does not throw an exception when a report contains an unsupported source type

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#1732]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/server/routes/plugins/injection_plugin.py", line 39, in wrapper
    return callback(*args, **kwargs)
  File "/home/server/routes/reports.py", line 25, in get_reports
    hide_credentials(data_model, *overview["reports"])
  File "/home/server/model/transformations.py", line 17, in hide_credentials
    if parameter_value and is_password_parameter(data_model, source["type"], parameter_key):
  File "/home/server/model/queries.py", line 10, in is_password_parameter
    parameter_type = data_model["sources"][source_type]["parameters"].get(parameter, dict(type="password"))["type"]
KeyError: 'owasp_dependency_check_jenkins_plugin'
INFO:root:<ip> - - [2020-12-07 09:36:21] "GET /api/v3/reports HTTP/1.1" 500 888 0.177938
```

**Comment by fniessink** [comment]
Can also happen with time travel:
```
INFO:root:x.x.x.x - - [2021-02-19 11:08:42] "GET /api/v3/datamodel?report_date=2021-02-09T22:59:59.000Z HTTP/1.1" 304 66 0.009389
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.9/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/server/routes/plugins/injection_plugin.py", line 41, in wrapper
    return callback(*args, **kwargs)
  File "/home/server/routes/reports.py", line 25, in get_reports
    hide_credentials(data_model, *overview["reports"])
  File "/home/server/model/transformations.py", line 17, in hide_credentials
    if parameter_value and is_password_parameter(data_model, source["type"], parameter_key):
  File "/home/server/model/queries.py", line 10, in is_password_parameter
    parameter_type = data_model["sources"][source_type]["parameters"].get(parameter, dict(type="password"))["type"]
KeyError: 'owasp_dependency_check_jenkins_plugin'
```
