### ISSUE TITLE
Traceback when getting data from Jenkins

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#1898]
The traceback happens with different metrics. There are other metrics that use the same Jenkins but succeed. Some of these metrics seem to fail more often than others. All Jenkins metrics in the report fail occasionally though.

Metric: tests
Source: Jenkins test report
Source URL: http://jenkins.example.org/job/Run%20JUnit%20tests/
Source username: example
Source password: *****
Source test results: all test results

Metric: failed CI-jobs
Source: Jenkins
Source URL:http://jenkins.example.org
Source username: example
Source password: *****
Jobs to include: all
Jobs to ignore: none
Failure types: failure

Metric: unused CI-jobs
Source: Jenkins
Source URL:http://jenkins.example.org
Source username: example
Source password: *****
Jobs to include: all
Jobs to ignore: none
Number of days without builds after which to consider CI-jobs unused: 90

```
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 104, in __safely_get_source_responses
    responses = await self._get_source_responses(api_url)
  File "/home/collector/base_collectors/source_collector.py", line 129, in _get_source_responses
    return SourceResponses(responses=list(await asyncio.gather(*tasks)), api_url=urls[0])
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1101, in send
    return self._coro.send(arg)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
RuntimeError: await wasn't used with future
```

**Comment by fniessink** [comment]
We have been unable to reproduce the issue reliably.
