### ISSUE TITLE
Exception in Sources tab for Metric

### ISSUE THREAD

**Issue by ds-o** [ICTU/quality-time#268]
When I open the Tests or Failed tests Metric (unauthenticated, Sonar Qube Source Type / SonarCloud), the Sources tab shows an exception:

![image](https://user-images.githubusercontent.com/21058511/56956313-16718f80-6b44-11e9-97fa-7a413b326a23.png)

Message:

```
Parse error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Quality_time_collector-0.1.0-py3.7.egg/src/collector.py", line 102, in safely_parse_source_response
    value = self.parse_source_response_value(response, **parameters)
  File "/usr/local/lib/python3.7/site-packages/Quality_time_collector-0.1.0-py3.7.egg/src/collectors/sonarqube.py", line 102, in parse_source_response_value
    return str(self._get_metrics(response)[self.metricKeys])
KeyError: 'tests'
```

**Comment by fniessink** [comment]
This is a feature, not a bug. The SonarQube instance doesn't have information on the number of test cases, so Quality-time hits an error trying to parse the number of test cases from the SonarQube response.
