### ISSUE TITLE
Connection error for metrics with Trello as source type

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#2901]
On multiple versions of QT a connection error occurs for the Metrics with Trello as source type:
- Source up-to-dateness
- Issues

API change?

Error:
`Connection error
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 91, in __safely_get_source_responses
    responses = await self._get_source_responses(api_url)
  File "/home/collector/source_collectors/trello/base.py", line 20, in _get_source_responses
    f"1/boards/{await self.__board_id()}?fields=id,url,dateLastActivity&lists=open&"
  File "/home/collector/source_collectors/trello/base.py", line 28, in __board_id
    boards = await (await super()._get_source_responses(url))[0].json()
  File "/home/collector/base_collectors/source_collector.py", line 118, in _get_source_responses
    raise response
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1125, in throw
    self._coro.throw(arg)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 466, in _request
    with timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError`

**Comment by fniessink** [comment]
I saw some timeouts with SonarQube as well this morning, probably due to a network connectivity interruption. Those timeouts have disappeared. Are the Trello timeouts still happening?

**Comment by denniebouman** [comment]
Trello timeouts have been resolved, the cause was probably this network connectivity interruption. Issue can be closed.
