### ISSUE TITLE
More flexible Axe-core JSON processing for Source version metric type

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#2910]
Feature request, add more flexible Axe-core JSON processing for "Source version" metric type. 
As the output of Axe-core is often aggregated by little custom scripts, be flexible in accepting different structures of the JSON format.

See also: https://github.com/ICTU/quality-time/issues/2657

**Comment by fniessink** [comment]
Parse error:

```
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 141, in __safely_parse_source_responses
    return await self._parse_source_responses(responses)
  File "/home/collector/base_collectors/source_collector.py", line 262, in _parse_source_responses
    versions = await self._parse_source_response_versions(responses)
  File "/home/collector/base_collectors/source_collector.py", line 267, in _parse_source_response_versions
    return await asyncio.gather(*[self._parse_source_response_version(response) for response in responses])
  File "/home/collector/source_collectors/axe_core/source_version.py", line 14, in _parse_source_response_version
    return Version((await response.json(content_type=None))["testEngine"]["version"])
TypeError: list indices must be integers or slices, not str
```
