### ISSUE TITLE
Parse error when trying to get the OWASP ZAP Report version

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#3117]
Parse error when trying to get the OWASP ZAP Report version from http://jenkins/job/OWASP-ZAP-scan/ws/report.xml:

`Parse error
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 141, in __safely_parse_source_responses
    return await self._parse_source_responses(responses)
  File "/home/collector/base_collectors/source_collector.py", line 262, in _parse_source_responses
    versions = await self._parse_source_response_versions(responses)
  File "/home/collector/base_collectors/source_collector.py", line 267, in _parse_source_response_versions
    return await asyncio.gather(*[self._parse_source_response_version(response) for response in responses])
  File "/home/collector/source_collectors/owasp_zap/source_version.py", line 15, in _parse_source_response_version
    return Version((await parse_source_response_xml(response)).get("version") or "0")
  File "/home/collector/venv/lib/python3.10/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'D-2021-12-20'`

In this report.xml the OWASPZAPReport version="D-2021-12-20" so this should be correct.

**Comment by fniessink** [comment]
Hmm, in what versioning scheme is `D-2021-12-20` a valid version number? Anyway, we can add a fallback mechanism to Quality-time where it uses a simple text compare if parsing a version number fails. That would mean that e.g. version `A-2021-12-01` is smaller/older than `B-2021-11-01`, but at least it would do something.

**Comment by fniessink** [comment]
Apparently, it's the version number for the weekly/daily version (https://www.zaproxy.org/download/). I'll make sure Quality-time can deal with this non-standard versioning scheme in the case of OWASP ZAP.
