### ISSUE TITLE
Connection Error with Gitlab source for metric 'Merge requests merged to master without approval'

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3166]
```python
Connection error
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 91, in __safely_get_source_responses
    responses = await self._get_source_responses(api_url)
  File "/home/collector/source_collectors/gitlab/merge_requests.py", line 82, in _get_source_responses
    response, has_next_page, cursor = await self._get_merge_request_response(client, approved_field, cursor)
  File "/home/collector/source_collectors/gitlab/merge_requests.py", line 102, in _get_merge_request_response
    page_info = json["data"]["project"]["mergeRequests"]["pageInfo"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by fniessink** [comment]
- Simulate the API call by hand to see what data GitLab returns
- Make this code more robust:

```python
async def _get_merge_request_response(
        self, client: GraphQLClient, approved_field: str, cursor: str = ""
    ) -> tuple[aiohttp.ClientResponse, bool, str]:
        """Return the merge request response, whether there are more pages, and a cursor to the next page, if any."""
        pagination = f'(after: "{cursor}")' if cursor else ""
        merge_request_query = MERGE_REQUEST_QUERY.format(pagination=pagination, approved=approved_field)
        response = await client.execute(merge_request_query, variables=dict(projectId=self._parameter("project")))
        json = await response.json()
        page_info = json["data"]["project"]["mergeRequests"]["pageInfo"] # ["mergeRequests"].get("pageInfo", {})
        return response, page_info["hasNextPage"], page_info.get("endCursor", "")  # page_info.get("hasNextPage", False)
```

**Comment by fniessink** [comment]
It seems something is wrong with the token you used. If I use a correct token, the data is retrieved from GitLab as expected. If I don't use a token or an invalid token, I get the same error as above.

Due to how the GraphQL API works, GitLab doesn't give a 403, but simply only returns the data you are allowed to see without proper authentication. Which is very limited. I'll try to add a more informative error message for when this happens again in the future.
