### ISSUE TITLE
Parse error when measuring source up-to-dateness of Jenkins test report

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#476]
Parse error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Quality_time_collector-0.5.0-py3.7.egg/src/source_collector.py", line 92, in safely_parse_source_responses
    value = self.parse_source_responses_value(responses)
  File "/usr/local/lib/python3.7/site-packages/Quality_time_collector-0.5.0-py3.7.egg/src/source_collectors/jenkins_test_report.py", line 66, in parse_source_responses_value
    return str(days_ago(parse(max(timestamps))))
ValueError: max() arg is an empty sequence
```

**Comment by fniessink** [comment]
False positive. The Jenkins test report didn't contain any timestamps.
