### ISSUE TITLE
Traceback when setting technical debt target (in dev environment)

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#6603]
```python
Traceback (most recent call last):
  File "/Users/fniessink/Developer/quality-time/components/api_server/venv/lib/python3.11/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/fniessink/Developer/quality-time/components/api_server/venv/lib/python3.11/site-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "/Users/fniessink/Developer/quality-time/components/api_server/src/routes/plugins/injection_plugin.py", line 49, in wrapper
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fniessink/Developer/quality-time/components/api_server/src/routes/plugins/auth_plugin.py", line 60, in wrapper
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fniessink/Developer/quality-time/components/api_server/src/routes/metric.py", line 159, in post_metric_debt
    new_end_date = (today + timedelta(days=report.desired_response_time("debt_target_met"))).isoformat()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fniessink/Developer/quality-time/components/api_server/src/model/report.py", line 39, in desired_response_time
    return int(self.get("desired_response_times", {}).get(status, default))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by fniessink** [comment]
Can't reproduce.
