### ISSUE TITLE
When starting Quality-time server locally with VPN enabled, gevent throws an error

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#695]
Gevent PR: https://github.com/gevent/gevent/pull/1429

Traceback:
```Traceback (most recent call last):
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/bottle.py", line 3127, in run
    server.run(app)
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/bottle.py", line 2922, in run
    server.serve_forever()
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/baseserver.py", line 367, in serve_forever
    self.start()
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/baseserver.py", line 305, in start
    self.init_socket()
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/pywsgi.py", line 1491, in init_socket
    self.update_environ()
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/pywsgi.py", line 1503, in update_environ
    name = socket.getfqdn(address[0])
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/_socketcommon.py", line 269, in getfqdn
    hostname, aliases, _ = gethostbyaddr(name)
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/_socketcommon.py", line 241, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/resolver/thread.py", line 68, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/_tblib.py", line 432, in load_traceback
    return loads(s)
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "/.../quality-time/components/server/venv/lib/python3.8/site-packages/gevent/_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
```

**Comment by fniessink** [comment]
Fixed by gevent 1.5a2.
